name: Continuous Training
on:
  push:
    branches:
      - workflow_continous_training
  schedule:
    - cron: '0 */6 * * *'  
  workflow_dispatch:
    imputs:
      reason:
        description: Why to run This?
        required: false
        default: running CT
jobs: 
  continous-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 
